# Generated by Django 4.1 on 2022-08-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.eventplace'),
        ),
    ]
