# Generated by Django 4.1 on 2022-08-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplace',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
