# Generated by Django 4.1 on 2022-08-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_eventplace_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_wedding',
            new_name='date_wedding',
        ),
    ]
