# Generated by Django 4.1 on 2022-08-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_data_wedding_order_date_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplace',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city'),
        ),
    ]
