# Generated by Django 4.1 on 2022-08-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
