# Generated by Django 4.1 on 2022-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Preparing'), ('2', 'Ready'), ('3', 'Done')], default='1', max_length=10),
        ),
    ]
