# Generated by Django 4.1 on 2022-08-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
    ]
